### ISSUE TITLE
several errors upon creating the CloudFormation stack

### ISSUE THREAD

**Issue by SebouhAra** [awslabs/aws-well-architected-labs#80] opened 2019-12-29 08:53 UTC
followed all instructions, receive this for CF events....at first I did not have unique S3 buckets I don't think. after I got past that, I renamed the new stack to DetectiveControls2 because it said the stack already existed even though it did not exist.

Later, I get this error - in 2 regions I try it in:
Unresolved resource dependencies [CloudTrailDestinationBucket] in the Outputs block of the template

**Comment by SebouhAra** [comment] 2019-12-29 08:54
Unresolved resource dependencies [CloudTrailDestinationBucket] in the Outputs block of the template

**Comment by setheliot** [comment] 2019-12-31 01:13
@benjipotter is this issue possibly for https://github.com/awslabs/aws-well-architected-labs/blob/master/Security/200_Automated_Deployment_of_Detective_Controls/Lab_Guide.md?

**Comment by SebouhAra** [comment] 2019-12-31 23:47
did I post this in the wrong section? yes, it's the 200 lab, Detective Controls that I had several issues deploying as instructed. Any logs I can provide?

**Comment by benjipotter** [comment] 2020-01-29 11:29
@SebouhAra please can you post the error messages you are receiving? We know that if you already have Guard Duty enabled then it will error on enabling that again. Its proven to work on a new account, existing accounts that may have had things like GD or Config enabled in the past can leave behind configuration items that conflict.

**Comment by oboyle** [comment] 2020-02-12 18:08
I was able to reproduce the error that @SebouhAra reported.

If you select 'No', for all of the services (CloudTrail, Config, GuardDuty), the template will fail because the output dependency is not met, generating the error from OP.

I was able to get around this by enabling only the CloudTrail service (I already had Config and GD set up) and specifying buckets to send the CloudTrail and Config audit to.

One way to fix this would be to not make CloudTrail setup optional. Arguably, if you don't need CloudTrail, you don't need this lab. Any other thoughts?

**Comment by benjipotter** [comment] 2020-06-26 09:05
I have fixed by making CloudTrail non-optional, and it will simply create an additional trail (and bucket, log group) if you have configured already. You can check it out now: https://www.wellarchitectedlabs.com/security/200_labs/200_automated_deployment_of_detective_controls/

**Closed by benjipotter** 2020-06-26 09:05 UTC
Labels: bug
